### ISSUE TITLE
Problem with dropping from blocks[]

### ISSUE THREAD

**Issue by Himegan420** [Mysticpasta1/Mystics-Monstrosity#10]
### Modpack

Mystic's Monstrosity 

### Game log

That's the problem during gameplay

### Description

When break blocks nothing drops. But when I kill a zombie it drops rotten flesh. Also when I click on berries bush It sound like I pick up berry but it doesn't appear in my eq.I tried to put up my own block and go break but it doesn't work either. I ran far from spawn and it still doesn't work. I really want to play this mod pack, please help

**Comment by Mysticpasta1** [comment]
I would need to know the version
